name: Build iOS App

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  # This specifies the macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Xcode for iOS build
        run: sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer

      - name: Build the iOS app
        run: flutter build ipa --release

      - name: Upload .ipa to GitHub artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa
